name: 'Build on push'
on: push
jobs:
  call-workflow-passing-data:
    uses: oracle-quickstart/appstack/.github/workflows/build.yml@${{github.ref_name}}
    with:
      branch: ${{github.ref_name}}
      type: 'java'
